//
// Created by Srdan Milakovic on 5/16/18.
//

#ifndef OPENSHMEM_COLLECTIVE_ROUTINES_GLOBAL_H
#define OPENSHMEM_COLLECTIVE_ROUTINES_GLOBAL_H

#include <shmem.h>

#define SHCOLL_BCAST_SYNC_SIZE 1

#define SHCOLL_SYNC_VALUE 0

/* TODO chose correct values */
#define SHCOLL_BARRIER_SYNC_SIZE SHMEM_BARRIER_SYNC_SIZE
#define SHCOLL_COLLECT_SYNC_SIZE SHMEM_COLLECT_SYNC_SIZE

#endif //OPENSHMEM_COLLECTIVE_ROUTINES_GLOBAL_H
